# Generated by Django 5.1.7 on 2025-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_payment_session_id_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(
                blank=True, help_text="Укажите Id продукта", max_length=255, null=True, verbose_name="Id продукта"
            ),
        ),
    ]
