# Generated by Django 5.1.7 on 2025-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(help_text="Укажите сумму платежа", verbose_name="Сумма платежа"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                help_text="Укажите способ оплаты",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
