# Generated by Django 5.1.7 on 2025-04-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_amount_alter_payment_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="product_id",
        ),
    ]
